### ISSUE TITLE
Crash when clicking a trace

### ISSUE THREAD

**Issue by noam-honig** [sboulema/StackTraceExplorer#5]
It crashes when I click a type or a method. When I click a file - it's ok.

Here is the crash:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at StackTraceExplorer.ClickHelper.HandleFunctionLinkClicked(System.String[])
   at StackTraceExplorer.CustomLinkVisualLineText.OnMouseDown(System.Windows.Input.MouseButtonEventArgs)
   at ICSharpCode.AvalonEdit.Rendering.TextView.OnMouseDown(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

The pasted stack was:
Last Menu Path: 
1) Programs
2) Orders

Short Callstack:
   at Northwind.Orders.ShowOrders.Details.Run() in C:\repos\copydatapath\Northwind.Orders\ShowOrders.cs:line 168
   at Northwind.Orders.ShowOrders.<>c.<InitializeDataViewAndUserFlow>b__8_8(Details c) in C:\repos\copydatapath\Northwind.Orders\ShowOrders.cs:line 72
   at Northwind.Orders.ShowOrders.Run() in C:\repos\copydatapath\Northwind.Orders\ShowOrders.cs:line 78
   at Northwind.Views.ApplicationMdi.<Orders_Click>b__59_0() in C:\Repos\copydatapath\Northwind\Views\ApplicationMdi.cs:line 375
   at Northwind.ApplicationCore.Execute() in C:\Repos\copydatapath\Northwind\ApplicationCore.cs:line 37
   at Northwind.ApplicationCore.Run() in C:\Repos\copydatapath\Northwind\ApplicationCore.cs:line 26
   at Northwind.Program.Main(String[] args) in C:\Repos\copydatapath\Northwind\Program.cs:line 12

Application Callstack:
Details - Northwind.Orders.ShowOrders+Details
Show Orders (P#5) - Northwind.Orders.ShowOrders

Open database connections:
NORTHWIND - NORTHWIND Datasource=(local)\sqlexpress;Catalog=Northwind;User=

Northwind Version: 3.4.24.30298
Firefly Version: 3.4.24.30304

**Comment by sboulema** [comment]
Thanks for reporting this bug!

Please try this new version: https://github.com/sboulema/StackTraceExplorer/releases/tag/v1.9.21

**Comment by noam-honig** [comment]
Tried it - it still crashes visual studio.

I uninstalled the previous version and installed 1.9.21.

Here is the new stack:
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at StackTraceExplorer.ClickHelper.HandleFunctionLinkClicked(System.String[])
   at StackTraceExplorer.CustomLinkVisualLineText.OnMouseDown(System.Windows.Input.MouseButtonEventArgs)
   at ICSharpCode.AvalonEdit.Rendering.TextView.OnMouseDown(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by noam-honig** [comment]
I've upgraded VS from version 15.3.4 to 15.7.1 and it solved the problem

**Comment by sboulema** [comment]
Good to hear!

**Comment by noam-honig** [comment]
Hi - this works great on version 15.7.1 of VS but, on a few older version I get that error

Version 15.3.4 and version 15.5.7 it still crashes - I think that not everyone updates to the latest release quickly, and they'll blame this extension for the crash, rather than know to upgrade to the latest vs.

You can either fix the crash on older versions, or somehow let the user know that it's requires VS version 15.7 and up.

**Comment by sboulema** [comment]
Will do some more testing, probably have to install that specific vs version in a VM, to reproduce and see what errors

**Comment by sboulema** [comment]
Reproduced the crash!

VS2017 15.6.6

`{"Could not load file or assembly 'Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.":"Microsoft.CodeAnalysis, Version=2.8.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}`

**Comment by sboulema** [comment]
Please try this new release: https://github.com/sboulema/StackTraceExplorer/releases/tag/v1.10.32
